### ISSUE TITLE
Delivery note - Return error

### ISSUE THREAD

**Issue by vwithv1602** [vwithv1602git1/erpnext_old_prod#5]
While making 'Sales Return' in Delivery Note, error is being thrown.

> Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 213, in insert
    self.run_method("after_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 559, in trigger_ebay_m2m_message
    send_ebay_m2m_message(itemid, subject, message_body_code, recipient,message_body_params)
  File "/home/frappe/frappe-bench/apps/erpnext_ebay/erpnext_ebay/utils.py", line 182, in send_ebay_m2m_message
    message_body = get_message_body_from_code(message_body_code,message_body_params)
  File "/home/frappe/frappe-bench/apps/erpnext_ebay/erpnext_ebay/utils.py", line 125, in get_message_body_from_code
    customer_name = message_body_params.get("customer_name")
AttributeError: 'str' object has no attribute 'get'

**Comment by vwithv1602** [comment]
Issue due to non-handling of 'Return' case while 'Delivery Note' is made.
Fix: https://github.com/vwithv1602git1/erpnext_old_prod/commit/194d899897731c1ab18a34dafc7f4834d4fd131c
